CREATE DATABASE PYTHON_SQL_PROJECT;

USE PYTHON_SQL_PROJECT;


SELECT * FROM STUDENT_PERFORMANCE;

-- Grades wise Student Count
SELECT
	GRADES,
    ROUND(COUNT(*) / (SELECT COUNT(*) FROM STUDENT_PERFORMANCE) * 100,2) AS PERCENTAGE
FROM STUDENT_PERFORMANCE
GROUP BY GRADES
ORDER BY PERCENTAGE DESC;

-- Distribution of Students by Gender
SELECT
	GENDER,
    ROUND(COUNT(*) / (SELECT COUNT(*) FROM STUDENT_PERFORMANCE) * 100,2) AS PERCENTAGE
FROM STUDENT_PERFORMANCE
GROUP BY GENDER
ORDER BY PERCENTAGE DESC; 

-- Count of Student by Gender
SELECT
	GENDER,
    COUNT(*) AS STUDENT_COUNT
FROM STUDENT_PERFORMANCE
GROUP BY GENDER;

-- Count of Student By Groups
SELECT
	`GROUP`,
    COUNT(*) AS STUDENT_COUNT
FROM STUDENT_PERFORMANCE
GROUP BY `GROUP`
ORDER BY STUDENT_COUNT DESC; 

-- Average Score by Subject
SELECT
	'MATH' AS SUBJECT,
	ROUND(AVG(MATH_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
UNION
SELECT
	'WRITING',
    ROUND(AVG(WRITING_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
UNION
SELECT	
	'READING',
    ROUND(AVG(READING_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE;

-- Average Score across all subject by gender
SELECT
	GENDER,
    ROUND(AVG(MATH_SCORE),2) AS MATH_AVERAGE_SCORE,
    ROUND(AVG(WRITING_SCORE),2) AS WRITING_AVERAGE_SCORE,
    ROUND(AVG(READING_SCORE),2) AS READING_AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
GROUP BY GENDER;

-- Student Average Score across Group
SELECT
	`GROUP`,
    ROUND(AVG(AVG_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
GROUP BY `GROUP`
ORDER BY AVERAGE_SCORE DESC;

-- Student Average Score by Parental Education
SELECT
	PARENTAL_EDUCATION,
    ROUND(AVG(AVG_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
GROUP BY PARENTAL_EDUCATION
ORDER BY AVERAGE_SCORE DESC;

-- Student Performance by Lunch Type
SELECT
	lunch,
    ROUND(AVG(AVG_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
GROUP BY lunch
ORDER BY AVERAGE_SCORE DESC;

-- Student Performance by Test Preparation Course
SELECT
	test_preparation_course,
    ROUND(AVG(AVG_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
GROUP BY test_preparation_course
ORDER BY AVERAGE_SCORE DESC;

-- Student Performance by Test Preparation Course and Gender
WITH cte as
(SELECT
	gender,
	test_preparation_course,
    ROUND(AVG(AVG_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
GROUP BY gender,test_preparation_course
ORDER BY AVERAGE_SCORE DESC)

SELECT
	GENDER,
    SUM(CASE WHEN test_preparation_course = 'completed' THEN AVERAGE_SCORE ELSE 0 END) AS COMPLETED,
    SUM(CASE WHEN test_preparation_course = 'NONE' THEN AVERAGE_SCORE ELSE 0 END) AS 'NONE'
FROM CTE
GROUP BY GENDER;

-- Student Performance by Test Preparation Course and GROUP
WITH cte as
(SELECT
	`GROUP`,
	test_preparation_course,
    ROUND(AVG(AVG_SCORE),2) AS AVERAGE_SCORE
FROM STUDENT_PERFORMANCE
GROUP BY `GROUP`,test_preparation_course
ORDER BY AVERAGE_SCORE DESC)

SELECT
	`GROUP`,
    SUM(CASE WHEN test_preparation_course = 'completed' THEN AVERAGE_SCORE ELSE 0 END) AS COMPLETED,
    SUM(CASE WHEN test_preparation_course = 'NONE' THEN AVERAGE_SCORE ELSE 0 END) AS 'NONE'
FROM CTE
GROUP BY `GROUP`;